name: Push directory to another repository
on: push
jobs:
  sync-to-azure:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/syncing-branch'
    steps:
    - uses: actions/checkout@v2
    - name: sync to azure
      env:
        AZREPO: "AzureRepos-syncing"
        AZPAT: ${{secrets.AZUREPAT}}
        AZUSERNAME: "s223125"
        AZUSER_EMAIL: "s223125@dtu.dk"
        AZORG: "s223125"
      shell: bash
      run: |
         chmod +x ./commit.sh
         ./commit.sh
